require('dotenv').config();
const express = require('express');
const cors = require('cors');
const multer = require('multer');
const Stripe = require('stripe');
const sgMail = require('@sendgrid/mail');
const { pool, initDb } = require('./db');

const app = express();
const upload = multer({
  storage: multer.memoryStorage(),
  limits: { fileSize: 50 * 1024 * 1024 } // 50MB
});

const stripe = new Stripe(process.env.STRIPE_SECRET_KEY);
sgMail.setApiKey(process.env.SENDGRID_API_KEY);

const FROM_EMAIL = process.env.SENDGRID_FROM_EMAIL || 'hello@lockdrop.co';
const FROM_NAME = process.env.SENDGRID_FROM_NAME || 'LockDrop';
const BASE_URL = process.env.BASE_URL || 'https://lockdrop.co';

// Raw body for Stripe webhooks
app.use('/webhooks/stripe', express.raw({ type: 'application/json' }));
app.use(express.json());
app.use(cors({
  origin: process.env.ALLOWED_ORIGIN || '*'
}));

// ─── POST /drops ────────────────────────────────────────────────────────────
app.post('/drops', upload.single('file'), async (req, res) => {
  try {
    const { freelancerEmail, clientEmail, projectName, amount, currency } = req.body;
    const file = req.file;

    if (!freelancerEmail || !clientEmail || !projectName || !amount || !file) {
      return res.status(400).json({ error: 'Missing required fields' });
    }

    const amountPence = Math.round(parseFloat(amount) * 100);
    if (isNaN(amountPence) || amountPence < 100) {
      return res.status(400).json({ error: 'Amount must be at least 1.00' });
    }

    const curr = (currency || 'gbp').toLowerCase();

    // Insert drop record (token auto-generated by DB)
    const insertResult = await pool.query(
      `INSERT INTO drops
         (freelancer_email, client_email, project_name, amount_pence, currency,
          file_name, file_data, file_size, file_mime)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
       RETURNING id, token`,
      [
        freelancerEmail, clientEmail, projectName, amountPence, curr,
        file.originalname,
        file.buffer,
        file.size,
        file.mimetype
      ]
    );

    const { id, token } = insertResult.rows[0];
    const dropUrl = `${BASE_URL}/drop/${token}`;

    // Create Stripe payment link
    let paymentUrl = null;
    let paymentLinkId = null;
    try {
      const price = await stripe.prices.create({
        unit_amount: amountPence,
        currency: curr,
        product_data: { name: `LockDrop: ${projectName}` }
      });
      const paymentLink = await stripe.paymentLinks.create({
        line_items: [{ price: price.id, quantity: 1 }],
        after_completion: {
          type: 'redirect',
          redirect: { url: dropUrl }
        },
        metadata: { drop_token: token, drop_id: id }
      });
      paymentUrl = paymentLink.url;
      paymentLinkId = paymentLink.id;

      await pool.query(
        `UPDATE drops SET stripe_payment_link_id=$1, stripe_payment_link_url=$2 WHERE id=$3`,
        [paymentLinkId, paymentUrl, id]
      );
    } catch (stripeErr) {
      console.error('Stripe error:', stripeErr.message);
      // Continue without payment link — drop still created
    }

    // Send email to client
    try {
      const currSymbol = curr === 'gbp' ? '£' : curr === 'eur' ? '€' : '$';
      const amountDisplay = `${currSymbol}${(amountPence / 100).toFixed(2)}`;

      await sgMail.send({
        to: clientEmail,
        from: { email: FROM_EMAIL, name: FROM_NAME },
        subject: `${freelancerEmail} has a file ready for you`,
        text: `Hi,

${freelancerEmail} has completed "${projectName}" and your file is ready.

To download it, pay ${amountDisplay}: ${paymentUrl || dropUrl}

Your file will unlock the moment payment clears.

— LockDrop
lockdrop.co`,
        html: `<p>Hi,</p>
<p><strong>${freelancerEmail}</strong> has completed <strong>"${projectName}"</strong> and your file is ready.</p>
<p>To download it, pay <strong>${amountDisplay}</strong>:</p>
<p><a href="${paymentUrl || dropUrl}" style="background:#10B981;color:#fff;padding:12px 24px;border-radius:6px;text-decoration:none;display:inline-block;font-weight:600;">Pay ${amountDisplay} to Download</a></p>
<p>Your file will unlock the moment payment clears.</p>
<br>
<p>— LockDrop<br><a href="https://lockdrop.co">lockdrop.co</a></p>`
      });
    } catch (emailErr) {
      console.error('Client email error:', emailErr.message);
    }

    // Send confirmation to freelancer
    try {
      const currSymbol = curr === 'gbp' ? '£' : curr === 'eur' ? '€' : '$';
      const amountDisplay = `${currSymbol}${(amountPence / 100).toFixed(2)}`;

      await sgMail.send({
        to: freelancerEmail,
        from: { email: FROM_EMAIL, name: FROM_NAME },
        subject: `Drop created — awaiting payment from ${clientEmail}`,
        text: `Your drop is live.

We've emailed ${clientEmail} with their payment link for ${amountDisplay}.
You'll receive an email the moment they pay.

Your drop link: ${dropUrl}

— LockDrop`,
        html: `<p>Your drop is live.</p>
<p>We've emailed <strong>${clientEmail}</strong> with their payment link for <strong>${amountDisplay}</strong>.</p>
<p>You'll receive an email the moment they pay.</p>
<p>Your drop link: <a href="${dropUrl}">${dropUrl}</a></p>
<br>
<p>— LockDrop<br><a href="https://lockdrop.co">lockdrop.co</a></p>`
      });
    } catch (emailErr) {
      console.error('Freelancer email error:', emailErr.message);
    }

    res.json({ token, dropUrl, paymentUrl });

  } catch (err) {
    console.error('POST /drops error:', err);
    res.status(500).json({ error: 'Internal server error' });
  }
});

// ─── GET /drops/:token ───────────────────────────────────────────────────────
app.get('/drops/:token', async (req, res) => {
  try {
    const { token } = req.params;
    const result = await pool.query(
      `SELECT paid, file_name, file_size, amount_pence, currency,
              project_name, stripe_payment_link_url, freelancer_email, client_email, created_at
       FROM drops WHERE token=$1`,
      [token]
    );
    if (!result.rows.length) return res.status(404).json({ error: 'Drop not found' });

    const drop = result.rows[0];
    const curr = drop.currency;
    const currSymbol = curr === 'gbp' ? '£' : curr === 'eur' ? '€' : '$';

    res.json({
      paid: drop.paid,
      fileName: drop.file_name,
      fileSize: drop.file_size,
      amountPence: drop.amount_pence,
      amountDisplay: `${currSymbol}${(drop.amount_pence / 100).toFixed(2)}`,
      currency: curr,
      projectName: drop.project_name,
      paymentUrl: drop.stripe_payment_link_url,
      freelancerEmail: drop.freelancer_email,
      clientEmail: drop.client_email,
      createdAt: drop.created_at
    });
  } catch (err) {
    console.error('GET /drops/:token error:', err);
    res.status(500).json({ error: 'Internal server error' });
  }
});

// ─── GET /drops/:token/download ──────────────────────────────────────────────
app.get('/drops/:token/download', async (req, res) => {
  try {
    const { token } = req.params;
    const result = await pool.query(
      `SELECT paid, file_name, file_data, file_mime, file_size FROM drops WHERE token=$1`,
      [token]
    );
    if (!result.rows.length) return res.status(404).json({ error: 'Drop not found' });

    const drop = result.rows[0];
    if (!drop.paid) {
      return res.status(402).json({ error: 'Payment required to download this file' });
    }

    // Mark as downloaded (first download only)
    await pool.query(
      `UPDATE drops SET downloaded_at=NOW() WHERE token=$1 AND downloaded_at IS NULL`,
      [token]
    );

    res.setHeader('Content-Type', drop.file_mime || 'application/octet-stream');
    res.setHeader('Content-Disposition', `attachment; filename="${drop.file_name}"`);
    if (drop.file_size) res.setHeader('Content-Length', drop.file_size);
    res.send(drop.file_data);

  } catch (err) {
    console.error('GET /drops/:token/download error:', err);
    res.status(500).json({ error: 'Internal server error' });
  }
});

// ─── POST /webhooks/stripe ───────────────────────────────────────────────────
app.post('/webhooks/stripe', async (req, res) => {
  const sig = req.headers['stripe-signature'];
  const webhookSecret = process.env.LOCKDROP_STRIPE_WEBHOOK_SECRET;

  let event;
  try {
    event = stripe.webhooks.constructEvent(req.body, sig, webhookSecret);
  } catch (err) {
    console.error('Webhook signature error:', err.message);
    return res.status(400).send(`Webhook Error: ${err.message}`);
  }

  if (
    event.type === 'checkout.session.completed' ||
    event.type === 'payment_intent.succeeded'
  ) {
    try {
      let token = null;
      let paymentIntentId = null;

      if (event.type === 'checkout.session.completed') {
        const session = event.data.object;
        // Get token from payment link metadata via the payment link ID
        token = session.metadata?.drop_token;
        paymentIntentId = session.payment_intent;

        // If no metadata on session, look up by payment link
        if (!token && session.payment_link) {
          const dbResult = await pool.query(
            `SELECT token FROM drops WHERE stripe_payment_link_id=$1`,
            [session.payment_link]
          );
          if (dbResult.rows.length) token = dbResult.rows[0].token;
        }
      } else if (event.type === 'payment_intent.succeeded') {
        paymentIntentId = event.data.object.id;
        token = event.data.object.metadata?.drop_token;
      }

      if (token) {
        const updateResult = await pool.query(
          `UPDATE drops
           SET paid=true, paid_at=NOW(), stripe_payment_intent_id=COALESCE($1, stripe_payment_intent_id)
           WHERE token=$2 AND paid=false
           RETURNING freelancer_email, client_email, project_name, amount_pence, currency`,
          [paymentIntentId, token]
        );

        if (updateResult.rows.length) {
          const drop = updateResult.rows[0];
          const curr = drop.currency;
          const currSymbol = curr === 'gbp' ? '£' : curr === 'eur' ? '€' : '$';
          const amountDisplay = `${currSymbol}${(drop.amount_pence / 100).toFixed(2)}`;
          const dropUrl = `${BASE_URL}/drop/${token}`;

          // Notify freelancer of payment
          try {
            await sgMail.send({
              to: drop.freelancer_email,
              from: { email: FROM_EMAIL, name: FROM_NAME },
              subject: `💰 Payment received for "${drop.project_name}"`,
              text: `${drop.client_email} just paid ${amountDisplay} for "${drop.project_name}".

They can now download their file.

Drop link: ${dropUrl}

— LockDrop`,
              html: `<p><strong>${drop.client_email}</strong> just paid <strong>${amountDisplay}</strong> for <strong>"${drop.project_name}"</strong>.</p>
<p>They can now download their file.</p>
<p><a href="${dropUrl}">${dropUrl}</a></p>
<br>
<p>— LockDrop<br><a href="https://lockdrop.co">lockdrop.co</a></p>`
            });
          } catch (emailErr) {
            console.error('Payment notification email error:', emailErr.message);
          }
        }
      }
    } catch (err) {
      console.error('Webhook processing error:', err);
    }
  }

  res.json({ received: true });
});

// ─── Health check ────────────────────────────────────────────────────────────
app.get('/health', (req, res) => res.json({ status: 'ok', ts: new Date() }));

// ─── Start ───────────────────────────────────────────────────────────────────
const PORT = process.env.PORT || 3001;

initDb()
  .then(() => {
    app.listen(PORT, () => console.log(`LockDrop API running on port ${PORT}`));
  })
  .catch(err => {
    console.error('Failed to init DB:', err);
    process.exit(1);
  });
